### ISSUE TITLE
Minimal feature set

### ISSUE THREAD

**Issue by hickford** [hickford/primesieve-python#1]
1. [x] List prime numbers up to n
2. [x] Count prime numbers up to n
3. [x] List first n prime numbers
4. [x] Calculate nth prime number
5. [x] Loop over prime numbers without bound

I think these are the most important features and would suffice for most uses. http://primesieve.org/api/

**Comment by kimwalisch** [comment]
> I think these are the most important features and would suffice for most uses. http://primesieve.org/api/

You are right, these are the most important features. But as adding other functions (e.g. the k-tuplet counting functions) is very simple I will probably fork your project and add these myself.

A few suggestions:

1) I think we should name the API functions the same way they are named in the C/C++ library. E.g. for primesieve::count_primes() we should name the Python function primesieve.count_primes(). This will reduce the confusion of the users.

2) Currently you are using the primesieve C bindings. I know Cython also supports C++ and the std::vector class which is quite handy. Using the primesieve C bindings there are no exceptions whereas if we use the primesieve C++ library we have proper exceptions (Cython supports C++ exceptions as far as I remember). What is the reason you chose primesieve.h over primesieve.hpp in your wrapper? Do you see any advantage in using the primesieve C bindings instead of the primesieve C++ library?

**Comment by hickford** [comment]
Great! Go for it. Thanks, I agree both. I'm very impressed with Cython. Tutorial was in C, but makes sense to use C++.

**Comment by hickford** [comment]
Top features done. Changed to use C++. Corrected function names to match C++.
